input.onButtonPressed(Button.A, function () {
    mewtcommand = 1
    serial.writeLine("" + (mewtcommand))
    basic.clearScreen()
    led.plot(0, 0)
    led.plot(0, 4)
    led.plot(1, 3)
    led.plot(1, 1)
    led.plot(2, 2)
    led.plot(3, 3)
    led.plot(3, 1)
    led.plot(4, 0)
    led.plot(4, 4)
})
serial.onDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    mewtstate = serial.readString()
    if (parseFloat(mewtstate) == 0) {
        basic.clearScreen()
        basic.setLedColor(0xff0000)
        led.plot(0, 0)
        led.plot(0, 4)
        led.plot(1, 3)
        led.plot(1, 1)
        led.plot(2, 2)
        led.plot(3, 3)
        led.plot(3, 1)
        led.plot(4, 0)
        led.plot(4, 4)
    } else if (parseFloat(mewtstate) >= 1 && parseFloat(mewtstate) <= 4) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
    } else if (parseFloat(mewtstate) >= 4 && parseFloat(mewtstate) <= 8) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
    } else if (parseFloat(mewtstate) >= 8 && parseFloat(mewtstate) <= 12) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
    } else if (parseFloat(mewtstate) >= 12 && parseFloat(mewtstate) <= 16) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
    } else if (parseFloat(mewtstate) >= 16 && parseFloat(mewtstate) <= 20) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
    } else if (parseFloat(mewtstate) >= 20 && parseFloat(mewtstate) <= 24) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
    } else if (parseFloat(mewtstate) >= 24 && parseFloat(mewtstate) <= 28) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
    } else if (parseFloat(mewtstate) >= 28 && parseFloat(mewtstate) <= 32) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
    } else if (parseFloat(mewtstate) >= 32 && parseFloat(mewtstate) <= 36) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
    } else if (parseFloat(mewtstate) >= 36 && parseFloat(mewtstate) <= 40) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
    } else if (parseFloat(mewtstate) >= 40 && parseFloat(mewtstate) <= 44) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
    } else if (parseFloat(mewtstate) >= 44 && parseFloat(mewtstate) <= 48) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
    } else if (parseFloat(mewtstate) >= 48 && parseFloat(mewtstate) <= 52) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
    } else if (parseFloat(mewtstate) >= 52 && parseFloat(mewtstate) <= 56) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
    } else if (parseFloat(mewtstate) >= 56 && parseFloat(mewtstate) <= 60) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
    } else if (parseFloat(mewtstate) >= 60 && parseFloat(mewtstate) <= 64) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
    } else if (parseFloat(mewtstate) >= 64 && parseFloat(mewtstate) <= 68) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
    } else if (parseFloat(mewtstate) >= 68 && parseFloat(mewtstate) <= 72) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
    } else if (parseFloat(mewtstate) >= 72 && parseFloat(mewtstate) <= 76) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
    } else if (parseFloat(mewtstate) >= 76 && parseFloat(mewtstate) <= 80) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
    } else if (parseFloat(mewtstate) >= 80 && parseFloat(mewtstate) <= 84) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
        led.plot(4, 4)
    } else if (parseFloat(mewtstate) >= 84 && parseFloat(mewtstate) <= 88) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
        led.plot(4, 4)
        led.plot(4, 3)
    } else if (parseFloat(mewtstate) >= 88 && parseFloat(mewtstate) <= 92) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
        led.plot(4, 4)
        led.plot(4, 3)
        led.plot(4, 2)
    } else if (parseFloat(mewtstate) >= 92 && parseFloat(mewtstate) <= 96) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
        led.plot(4, 4)
        led.plot(4, 3)
        led.plot(4, 2)
        led.plot(4, 1)
    } else if (parseFloat(mewtstate) >= 96 && parseFloat(mewtstate) <= 100) {
        basic.clearScreen()
        basic.setLedColor(0x0000ff)
        led.plot(0, 4)
        led.plot(0, 3)
        led.plot(0, 2)
        led.plot(0, 1)
        led.plot(0, 0)
        led.plot(1, 4)
        led.plot(1, 3)
        led.plot(1, 2)
        led.plot(1, 1)
        led.plot(1, 0)
        led.plot(2, 4)
        led.plot(2, 3)
        led.plot(2, 2)
        led.plot(2, 1)
        led.plot(2, 0)
        led.plot(3, 4)
        led.plot(3, 3)
        led.plot(3, 2)
        led.plot(3, 1)
        led.plot(3, 0)
        led.plot(4, 4)
        led.plot(4, 3)
        led.plot(4, 2)
        led.plot(4, 1)
        led.plot(4, 0)
    }
})
input.onButtonPressed(Button.B, function () {
    mewtcommand = 0
    serial.writeLine("" + (mewtcommand))
    basic.clearScreen()
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(1, 0)
    led.plot(1, 4)
    led.plot(2, 0)
    led.plot(2, 4)
    led.plot(3, 0)
    led.plot(3, 4)
    led.plot(4, 1)
    led.plot(4, 2)
    led.plot(4, 3)
})
let mewtstate = ""
let mewtcommand = 0
serial.setBaudRate(BaudRate.BaudRate9600)
mewtcommand = 1
serial.writeLine("" + (mewtcommand))
basic.clearScreen()
basic.setLedColor(0x00ff00)
